name: Update File

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update file
        run: |
          echo "Updated content" > js/file_urls.txt

          rm file_urls.txt

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "kimwiz4352@gmail.com"
          git add js/file_urls.txt
          git rm file_urls.txt
          git commit -m "Auto-update js/file_urls.txt and remove file_urls.txt [skip ci]"
          git push
